In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Data/gemstone.csv")
df

id  carat        cut color clarity  depth  table     x     y  \
0            0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33   
1            1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12   
2            2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73   
3            3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41   
4            4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61   
...        ...    ...        ...   ...     ...    ...    ...   ...   ...   
193568  193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39   
193569  193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77   
193570  193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75   
193571  193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49   
193572  193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71   

           z  price  
0       4.55  13619  
1       5.05  13387  
2       3.50   2772  
3       2.71    666  
4       4.77  14453  
...      ...    ...  
193568  2.67   1130  
193569  3.47   2874  
193570  3.62   3036  
193571  2.81    681  
193572  3.48   2258  

[193573 rows x 11 columns]

In [4]:
df=df.drop(labels=['id'],axis=1)

In [5]:
# dependent and independant
X=df.drop(labels=["price"],axis=1)
Y=df[["price"]]


In [6]:
X

carat        cut color clarity  depth  table     x     y     z
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 9 columns]

In [7]:
Y

price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [8]:
# Define which columns should be ordinal-encoded and which should be scaled
categorical_cols = X.select_dtypes(include="object").columns
numerical_cols = X.select_dtypes(exclude="object").columns

In [9]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [10]:
# import scikit-learn on requirements and run
# or do pip install scikit-learn in terminal

In [11]:
from sklearn.impute import SimpleImputer #(fillna) fills mean /median/mode #handles missing values
from sklearn.preprocessing import StandardScaler # it will standardize your distribution #does feature scaling
from sklearn.preprocessing import OrdinalEncoder #ordinal encoding
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [12]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories])),
    ('scaler',StandardScaler())
    ]

)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])


In [13]:
# train-test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,train_size=0.3,random_state=30)

In [14]:
preprocessor.fit_transform(X_train)

array([[ 1.5578769 ,  1.09880974,  3.00679907, ..., -1.14988979,
         0.30148996,  0.01413387],
       [-1.05877362, -0.10555455, -0.6416552 , ...,  0.87335739,
         2.15560852,  0.68034151],
       [ 0.23873904,  1.37673996,  1.44317581, ..., -1.14988979,
        -0.93458908, -1.31828142],
       ...,
       [ 0.45499114,  1.56202677, -0.6416552 , ..., -2.16151339,
         0.30148996, -0.65207378],
       [ 0.67124325, -1.77313588,  1.44317581, ...,  0.87335739,
         0.30148996,  0.68034151],
       [ 0.26036425,  0.82087952, -0.12044745, ...,  0.87335739,
         0.30148996, -0.65207378]])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193573 entries, 0 to 193572
Data columns (total 10 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   carat    193573 non-null  float64
 1   cut      193573 non-null  object 
 2   color    193573 non-null  object 
 3   clarity  193573 non-null  object 
 4   depth    193573 non-null  float64
 5   table    193573 non-null  float64
 6   x        193573 non-null  float64
 7   y        193573 non-null  float64
 8   z        193573 non-null  float64
 9   price    193573 non-null  int64  
dtypes: float64(6), int64(1), object(3)
memory usage: 14.8+ MB


In [16]:
pd.DataFrame(preprocessor.fit_transform(X_train))

0         1         2         3         4         5         6  \
0      1.557877  1.098810  3.006799  1.294531  1.343913  1.453784 -1.149890   
1     -1.058774 -0.105555 -0.641655 -1.245048 -1.220791 -1.240980  0.873357   
2      0.238739  1.376740  1.443176  0.339937  0.365157  0.477842 -1.149890   
3     -0.193765 -0.754058  0.921968 -0.038298 -0.015471 -0.104809 -0.138266   
4      1.557877  0.542949  0.400760  1.492654  1.461726  1.526615 -0.138266   
...         ...       ...       ...       ...       ...       ...       ...   
58066 -1.037148 -0.012911 -0.641655 -1.263059 -1.238916 -1.240980  0.873357   
58067  0.995621  0.172376 -0.641655  1.051380  1.117349  1.089627  0.873357   
58068  0.454991  1.562027 -0.641655  0.520049  0.591721  0.710903 -2.161513   
58069  0.671243 -1.773136  1.443176  0.871268  0.954223  0.696337  0.873357   
58070  0.260364  0.820880 -0.120447  0.384965  0.419532  0.477842  0.873357   

              7         8  
0      0.301490  0.014134  
1      2.155609  0.680342  
2     -0.934589 -1.318281  
3     -0.934589  0.680342  
4     -0.316550 -1.318281  
...         ...       ...  
58066 -0.934589 -0.652074  
58067  0.301490 -1.318281  
58068  0.301490 -0.652074  
58069  0.301490  0.680342  
58070  0.301490 -0.652074  

[58071 rows x 9 columns]

In [17]:
# now add proper columns to it
pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())

num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0                 1.557877             1.098810             3.006799   
1                -1.058774            -0.105555            -0.641655   
2                 0.238739             1.376740             1.443176   
3                -0.193765            -0.754058             0.921968   
4                 1.557877             0.542949             0.400760   
...                    ...                  ...                  ...   
58066            -1.037148            -0.012911            -0.641655   
58067             0.995621             0.172376            -0.641655   
58068             0.454991             1.562027            -0.641655   
58069             0.671243            -1.773136             1.443176   
58070             0.260364             0.820880            -0.120447   

       num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0             1.294531         1.343913         1.453784          -1.149890   
1            -1.245048        -1.220791        -1.240980           0.873357   
2             0.339937         0.365157         0.477842          -1.149890   
3            -0.038298        -0.015471        -0.104809          -0.138266   
4             1.492654         1.461726         1.526615          -0.138266   
...                ...              ...              ...                ...   
58066        -1.263059        -1.238916        -1.240980           0.873357   
58067         1.051380         1.117349         1.089627           0.873357   
58068         0.520049         0.591721         0.710903          -2.161513   
58069         0.871268         0.954223         0.696337           0.873357   
58070         0.384965         0.419532         0.477842           0.873357   

       cat_pipeline__color  cat_pipeline__clarity  
0                 0.301490               0.014134  
1                 2.155609               0.680342  
2                -0.934589              -1.318281  
3                -0.934589               0.680342  
4                -0.316550              -1.318281  
...                    ...                    ...  
58066            -0.934589              -0.652074  
58067             0.301490              -1.318281  
58068             0.301490              -0.652074  
58069             0.301490               0.680342  
58070             0.301490              -0.652074  

[58071 rows x 9 columns]

In [18]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())

In [19]:
X_train

num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0                 1.557877             1.098810             3.006799   
1                -1.058774            -0.105555            -0.641655   
2                 0.238739             1.376740             1.443176   
3                -0.193765            -0.754058             0.921968   
4                 1.557877             0.542949             0.400760   
...                    ...                  ...                  ...   
58066            -1.037148            -0.012911            -0.641655   
58067             0.995621             0.172376            -0.641655   
58068             0.454991             1.562027            -0.641655   
58069             0.671243            -1.773136             1.443176   
58070             0.260364             0.820880            -0.120447   

       num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0             1.294531         1.343913         1.453784          -1.149890   
1            -1.245048        -1.220791        -1.240980           0.873357   
2             0.339937         0.365157         0.477842          -1.149890   
3            -0.038298        -0.015471        -0.104809          -0.138266   
4             1.492654         1.461726         1.526615          -0.138266   
...                ...              ...              ...                ...   
58066        -1.263059        -1.238916        -1.240980           0.873357   
58067         1.051380         1.117349         1.089627           0.873357   
58068         0.520049         0.591721         0.710903          -2.161513   
58069         0.871268         0.954223         0.696337           0.873357   
58070         0.384965         0.419532         0.477842           0.873357   

       cat_pipeline__color  cat_pipeline__clarity  
0                 0.301490               0.014134  
1                 2.155609               0.680342  
2                -0.934589              -1.318281  
3                -0.934589               0.680342  
4                -0.316550              -1.318281  
...                    ...                    ...  
58066            -0.934589              -0.652074  
58067             0.301490              -1.318281  
58068             0.301490              -0.652074  
58069             0.301490               0.680342  
58070             0.301490              -0.652074  

[58071 rows x 9 columns]

In [20]:
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [23]:
# why we used transform and not fit . now we want to test it 
# data leakage

In [21]:
X_test

num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0                 -0.561394            -0.939345            -0.641655   
1                 -0.172140             1.006166            -0.120447   
2                 -1.058774             0.265019            -0.120447   
3                  0.973996            -0.198198             1.964384   
4                 -0.929022            -1.309919             0.400760   
...                     ...                  ...                  ...   
135497            -1.037148            -0.476128            -1.162863   
135498            -1.015523            -0.939345            -0.641655   
135499            -0.496518            -0.383485            -0.641655   
135500            -1.037148             0.079732            -0.641655   
135501            -0.172140            -0.661415             1.443176   

        num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0             -0.425538        -0.459536        -0.498099          -0.138266   
1             -0.038298        -0.024533         0.040854          -1.149890   
2             -1.299081        -1.293291        -1.270113           0.873357   
3              1.051380         0.999536         0.987663          -0.138266   
4             -1.001897        -0.985164        -1.066184          -0.138266   
...                 ...              ...              ...                ...   
135497        -1.200020        -1.202666        -1.226414           0.873357   
135498        -1.173003        -1.148290        -1.226414           0.873357   
135499        -0.371505        -0.350785        -0.396135           0.873357   
135500        -1.236042        -1.220791        -1.211847           0.873357   
135501         0.024741        -0.006408        -0.046544          -0.138266   

        cat_pipeline__color  cat_pipeline__clarity  
0                 -0.934589               0.014134  
1                  0.919529              -0.652074  
2                  0.919529               2.678964  
3                  0.301490               0.014134  
4                 -0.934589               0.680342  
...                     ...                    ...  
135497            -0.316550               2.012757  
135498             0.301490               2.012757  
135499            -0.934589              -0.652074  
135500            -1.552629              -0.652074  
135501             0.301490              -1.318281  

[135502 rows x 9 columns]

In [24]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [26]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [27]:
regression.coef_

array([[ 6354.46770828,   -97.00399344,   -65.92958073, -1901.98734577,
           39.38259013,  -351.00370492,    71.8723543 ,  -455.58379747,
          654.21977009]])

In [28]:
regression.intercept_

array([3961.26553702])

In [50]:
mypred=regression.predict(X_test)

In [51]:
mypred

array([[1918.5295865 ],
       [1907.11477419],
       [1477.75216037],
       ...,
       [1779.44251387],
       [ 477.05378369],
       [1795.70916941]])

In [35]:
pd.DataFrame(mypred)

0
0       1918.529587
1       1907.114774
2       1477.752160
3       7595.143729
4       1260.438401
...             ...
135497  1682.897253
135498  1500.071906
135499  1779.442514
135500   477.053784
135501  1795.709169

[135502 rows x 1 columns]

In [55]:
dfpred = pd.DataFrame(mypred)
print(dfpred.iloc[0])

0    1918.529587
Name: 0, dtype: float64


In [56]:
pd.DataFrame(y_test)

price
70432    1607
64839    2211
185316    764
84658    7655
31953     735
...       ...
95508     840
168089    815
134143   1712
47205     571
93559    2146

[135502 rows x 1 columns]

In [57]:
df_y_test = pd.DataFrame(y_test)
print(df_y_test.iloc[0])

price    1607
Name: 70432, dtype: int64


In [59]:
# comparing both again at 1st index
dfpred = pd.DataFrame(mypred)
print(dfpred.iloc[1])

df_y_test = pd.DataFrame(y_test)
print(df_y_test.iloc[1])

0    1907.114774
Name: 1, dtype: float64
price    2211
Name: 64839, dtype: int64


In [60]:
# comparing both again at 2nd index
dfpred = pd.DataFrame(mypred)
print(dfpred.iloc[2])

df_y_test = pd.DataFrame(y_test)
print(df_y_test.iloc[2])

0    1477.75216
Name: 2, dtype: float64
price    764
Name: 185316, dtype: int64


In [61]:
# comparing both again at 3rd index
dfpred = pd.DataFrame(mypred)
print(dfpred.iloc[3])

df_y_test = pd.DataFrame(y_test)
print(df_y_test.iloc[3])

0    7595.143729
Name: 3, dtype: float64
price    7655
Name: 84658, dtype: int64


In [62]:
# comparing both again at 4th index
dfpred = pd.DataFrame(mypred)
print(dfpred.iloc[4])

df_y_test = pd.DataFrame(y_test)
print(df_y_test.iloc[4])

0    1260.438401
Name: 4, dtype: float64
price    735
Name: 31953, dtype: int64


In [63]:
# comparing both again at 5th index
dfpred = pd.DataFrame(mypred)
print(dfpred.iloc[5])

df_y_test = pd.DataFrame(y_test)
print(df_y_test.iloc[5])

0    2733.476497
Name: 5, dtype: float64
price    3043
Name: 111121, dtype: int64


In [69]:
# comparing both again at 6th index
dfpred = pd.DataFrame(mypred)
dfpred = dfpred.rename(columns={0: 'our prediction'})
print(dfpred.iloc[6])

df_y_test = pd.DataFrame(y_test)
print(df_y_test.iloc[6])

our prediction    5001.65805
Name: 6, dtype: float64
price    4925
Name: 40829, dtype: int64


In [68]:
# comparing both again at 2nd index
dfpred = pd.DataFrame(mypred)

dfpred = dfpred.rename(columns={0: 'our prediction'})
print(dfpred.iloc[6])


print(dfpred.iloc[10:16])

df_y_test = pd.DataFrame(y_test)
print(df_y_test.iloc[10:16])

our prediction    5001.65805
Name: 6, dtype: float64
    our prediction
10     6980.566373
11     3593.772723
12     8784.662108
13     4895.575091
14     5665.554914
15     5450.901015
        price
147036   6733
101963   3180
14972    5832
57509    4429
103069   6532
190687   5636
